version: '3'

vars:
  DOTNET_ENVIRONMENT: Development

tasks:

  # ----------------------------------
  # Start PostgreSQL dev database
  # ----------------------------------
  up-db:
    desc: "Start PostgreSQL development database container"
    cmds:
      - docker compose up -d

  # ----------------------------------
  # Run .NET backend
  # ----------------------------------
  api:
    desc: "Run .NET backend"
    dir: backend/src/Domino.Backend
    ignore_error: true
    cmds:
      - task: api-restore
      - |
        if [ "${WATCH}" = "true" ]; then
          echo "Starting .NET backend in WATCH mode..."
          DOTNET_ENVIRONMENT={{.DOTNET_ENVIRONMENT}} dotnet watch run
        else
          echo "Starting .NET backend..."
          DOTNET_ENVIRONMENT={{.DOTNET_ENVIRONMENT}} dotnet run
        fi

  api-restore:
    desc: "Restore .NET dependencies"
    dir: backend/src/Domino.Backend
    cmds:
      - dotnet restore

  # ----------------------------------
  # Run React frontend
  # ----------------------------------
  client:
    desc: "Run React frontend"
    dir: frontend
    ignore_error: true
    cmds:
      - npm install
      - |
        if [ "${WATCH}" = "true" ]; then
          echo "Starting React frontend in WATCH mode..."
          npm run dev
        else
          echo "Starting React frontend..."
          npm start
        fi

  # ----------------------------------
  # Tail PostgreSQL logs
  # ----------------------------------
  db-logs:
    desc: "Tail PostgreSQL container logs"
    ignore_error: true
    cmds:
      - docker logs -f dev-postgres

  # ----------------------------------
  # Full dev environment
  # ----------------------------------
  dev:
    desc: "Start DB, backend, frontend, and PostgreSQL logs"
    preconditions:
      - "docker --version || { echo 'Docker is required!'; exit 1; }"
    cmds:
      - task: up-db
      - |
        task api &
        task client &
        task db-logs &
        wait || true

  # ----------------------------------
  # Start without hot reload
  # ----------------------------------
  start:
    desc: "Start backend and frontend (no watch)"
    cmds:
      - WATCH=false task dev

  # ----------------------------------
  # Start with hot reload
  # ----------------------------------
  watch:
    desc: "Start backend and frontend with watch mode"
    cmds:
      - WATCH=true task dev
